### ISSUE TITLE
1.2.4 overwriting project-level package.json file

### ISSUE THREAD

**Issue by johnkcox** [dpa99c/cordova-custom-config#33] opened 2016-02-10 22:56 UTC
Greetings again. Our application grabbed your 1.2.4 update and we noticed that when it ran it overwrote our project-level package.json file. Is this something that happened with 1.2.4 or is it more of a timing issue?

**Comment by dpa99c** [comment] 2016-02-11 08:23
1.2.4 only contains 2 minor fixes: [Remove lodash compatibility hack](a563d05ea63731a659c6087610fdf90fb5c3b514) and [Fix non-resolution of promise if config is set to skip auto-backup/restore](ae219a27382000ecf1618e91ee880282271764f5) so it's unlikely either of these commits changed the behaviour since 1.2.3 with regard to project-level package.json, but I will regression test it tonight (~20:00 GMT+0)

**Comment by dpa99c** [comment] 2016-02-11 21:04
hmm, can't reproduce it this time, so possible race condition :-(

What cordova operation were you running when you observed it (prepare/build/platform add)?

Any chance you can run the operation with --verbose CLI argument and post the result?

**Comment by GitRubb** [comment] 2016-02-15 04:31
Same issue here, package.json is overwritten (currently on cordova 6 and custom config 1.2.4). This did not happen for me on cordova 5.4.1 and custom config 1.1.8.

**Comment by mikechamberlain** [comment] 2016-02-25 05:20
Same for me - with cordova 5.3.3.  It happened on the Build stage, not Prepare.  Here is the relevant output:

```
mikebook:client mikechamberlain$ cordova plugin add cordova-custom-config --verbose
no version specified, retrieving version from config.xml
Calling plugman.fetch on plugin "cordova-custom-config"
Fetching plugin "cordova-custom-config" via npm
Copying plugin "/Users/mikechamberlain/.npm/cordova-custom-config/1.2.4/package" => "/Users/mikechamberlain/dev/simple/client/plugins/cordova-custom-config"
Calling plugman.install on plugin "/Users/mikechamberlain/dev/simple/client/plugins/cordova-custom-config" for platform "ios" with options "{"cli_variables":{},"browserify":false,"link":false,"pluginInfoProvider":{"_cache":{"/Users/mikechamberlain/.npm/cordova-custom-config/1.2.4/package":{"filepath":"/Users/mikechamberlain/.npm/cordova-custom-config/1.2.4/package/plugin.xml","dir":"/Users/mikechamberlain/.npm/cordova-custom-config/1.2.4/package","_et":{"_root":{"_id":818,"tag":"plugin","attrib":{"xmlns":"http://www.phonegap.com/ns/plugins/1.0","xmlns:android":"http://schemas.android.com/apk/res/android","id":"cordova-custom-config","version":"1.2.4"},"text":"\r\n\r\n    ","tail":null,"_children":[{"_id":819,"tag":"name","attrib":{},"text":"cordova-custom-config","tail":"\r\n    ","_children":[]},{"_id":820,"tag":"description","attrib":{},"text":"Cordova/Phonegap plugin to update platform configuration files based on preferences and config-file data defined in config.xml","tail":"\r\n    ","_children":[]},{"_id":821,"tag":"author","attrib":{},"text":"Dave Alden","tail":"\r\n\r\n    ","_children":[]},{"_id":822,"tag":"engines","attrib":{},"text":"\r\n        ","tail":"\r\n\r\n    ","_children":[{"_id":823,"tag":"engine","attrib":{"name":"cordova","version":">=3.0.0"},"text":"","tail":"\r\n    ","_children":[]}]},{"_id":824,"tag":"repo","attrib":{},"text":"https://github.com/dpa99c/cordova-custom-config.git","tail":"\r\n    ","_children":[]},{"_id":825,"tag":"issue","attrib":{},"text":"https://github.com/dpa99c/cordova-custom-config/issues","tail":"\r\n\r\n    ","_children":[]},{"_id":826,"tag":"keywords","attrib":{},"text":"ecosystem:cordova,cordova,phonegap,ios,android,config,configuration,plist,manifest","tail":"\r\n\r\n    ","_children":[]},{"_id":827,"tag":"license","attrib":{},"text":"MIT","tail":"\r\n\r\n    ","_children":[]},{"_id":828,"tag":"hook","attrib":{"src":"hooks/restoreBackups.js","type":"before_prepare"},"text":"","tail":"\r\n    ","_children":[]},{"_id":829,"tag":"hook","attrib":{"src":"hooks/restoreBackups.js","type":"before_plugin_uninstall"},"text":"","tail":"\r\n    ","_children":[]},{"_id":830,"tag":"hook","attrib":{"src":"hooks/applyCustomConfig.js","type":"after_prepare"},"text":"","tail":"\r\n    ","_children":[]},{"_id":831,"tag":"hook","attrib":{"src":"hooks/resolveDependencies.js","type":"after_plugin_install"},"text":"","tail":"\r\n    ","_children":[]},{"_id":832,"tag":"hook","attrib":{"src":"hooks/resolveDependencies.js","type":"before_platform_add"},"text":"","tail":"\r\n","_children":[]}]}},"id":"cordova-custom-config","version":"1.2.4","name":"cordova-custom-config","description":"Cordova/Phonegap plugin to update platform configuration files based on preferences and config-file data defined in config.xml","license":"MIT","repo":"https://github.com/dpa99c/cordova-custom-config.git","issue":"https://github.com/dpa99c/cordova-custom-config/issues","keywords":["ecosystem:cordova","cordova","phonegap","ios","android","config","configuration","plist","manifest"]},"/Users/mikechamberlain/dev/simple/client/plugins/cordova-custom-config":{"filepath":"/Users/mikechamberlain/dev/simple/client/plugins/cordova-custom-config/plugin.xml","dir":"/Users/mikechamberlain/dev/simple/client/plugins/cordova-custom-config","_et":{"_root":{"_id":833,"tag":"plugin","attrib":{"xmlns":"http://www.phonegap.com/ns/plugins/1.0","xmlns:android":"http://schemas.android.com/apk/res/android","id":"cordova-custom-config","version":"1.2.4"},"text":"\r\n\r\n    ","tail":null,"_children":[{"_id":834,"tag":"name","attrib":{},"text":"cordova-custom-config","tail":"\r\n    ","_children":[]},{"_id":835,"tag":"description","attrib":{},"text":"Cordova/Phonegap plugin to update platform configuration files based on preferences and config-file data defined in config.xml","tail":"\r\n    ","_children":[]},{"_id":836,"tag":"author","attrib":{},"text":"Dave Alden","tail":"\r\n\r\n    ","_children":[]},{"_id":837,"tag":"engines","attrib":{},"text":"\r\n        ","tail":"\r\n\r\n    ","_children":[{"_id":838,"tag":"engine","attrib":{"name":"cordova","version":">=3.0.0"},"text":"","tail":"\r\n    ","_children":[]}]},{"_id":839,"tag":"repo","attrib":{},"text":"https://github.com/dpa99c/cordova-custom-config.git","tail":"\r\n    ","_children":[]},{"_id":840,"tag":"issue","attrib":{},"text":"https://github.com/dpa99c/cordova-custom-config/issues","tail":"\r\n\r\n    ","_children":[]},{"_id":841,"tag":"keywords","attrib":{},"text":"ecosystem:cordova,cordova,phonegap,ios,android,config,configuration,plist,manifest","tail":"\r\n\r\n    ","_children":[]},{"_id":842,"tag":"license","attrib":{},"text":"MIT","tail":"\r\n\r\n    ","_children":[]},{"_id":843,"tag":"hook","attrib":{"src":"hooks/restoreBackups.js","type":"before_prepare"},"text":"","tail":"\r\n    ","_children":[]},{"_id":844,"tag":"hook","attrib":{"src":"hooks/restoreBackups.js","type":"before_plugin_uninstall"},"text":"","tail":"\r\n    ","_children":[]},{"_id":845,"tag":"hook","attrib":{"src":"hooks/applyCustomConfig.js","type":"after_prepare"},"text":"","tail":"\r\n    ","_children":[]},{"_id":846,"tag":"hook","attrib":{"src":"hooks/resolveDependencies.js","type":"after_plugin_install"},"text":"","tail":"\r\n    ","_children":[]},{"_id":847,"tag":"hook","attrib":{"src":"hooks/resolveDependencies.js","type":"before_platform_add"},"text":"","tail":"\r\n","_children":[]}]}},"id":"cordova-custom-config","version":"1.2.4","name":"cordova-custom-config","description":"Cordova/Phonegap plugin to update platform configuration files based on preferences and config-file data defined in config.xml","license":"MIT","repo":"https://github.com/dpa99c/cordova-custom-config.git","issue":"https://github.com/dpa99c/cordova-custom-config/issues","keywords":["ecosystem:cordova","cordova","phonegap","ios","android","config","configuration","plist","manifest"]}},"_getAllCache":{}}}"
Plugin "cordova-custom-config" already installed on ios.
mikebook:client mikechamberlain$ cordova prepare --verbose
cordova-custom-config: Running restoreBackups.js
cordova-custom-config: package.json already exists
cordova-custom-config: Copied existing package.json to package.json.tmp
cordova-custom-config: Copying package.json
cordova-custom-config: Copied package.json
cordova-custom-config: Installing plugin dependencies...
cordova-custom-config: Running npm install
cordova-custom-config: Completed npm install
cordova-custom-config: Installed modules
cordova-custom-config: package.json.tmp exists
cordova-custom-config: Overwrote our package.json with original package.json.tmp
cordova-custom-config: Removing package.json.tmp
cordova-custom-config: Removed package.json.tmp
cordova-custom-config: Dependency resolution complete
cordova-custom-config: Checking to see if there are backups to restore...
cordova-custom-config: Finished restoring backups
Generating config.xml from defaults for platform "ios"
Calling plugman.prepare for platform "ios"
Preparing ios project
Processing configuration changes for plugins.
Iterating over installed plugins: [ 'cordova-plugin-whitelist',
  'cordova-plugin-customurlscheme',
  'cordova-plugin-inappbrowser',
  'cordova-plugin-statusbar',
  'org.apache.cordova.splashscreen',
  'cordova-plugin-app-version',
  'cordova-plugin-network-information',
  'cordova-plugin-appavailability',
  'nl.x-services.plugins.touchid',
  'com.shazron.cordova.plugin.keychainutil',
  'cordova-plugin-x-socialsharing',
  'phonegap-plugin-push',
  'cordova-plugin-badge',
  'cordova-custom-config',
  'cordova-plugin-app-event' ]
Writing out cordova_plugins.js...
Wrote out iOS Bundle Identifier to "com.macquarie.cog.digital.simple"
Wrote out iOS Bundle Version to "1.4.0"
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/60 Home Screen.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-60.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/120 Retina Home Screen.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-60@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/180 Retina App Icon.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-60@3x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/76 Home Screen.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-76.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/152 Retina Home Screen.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-76@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/29 Settings.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-small.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/58 Retina Setting.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-small@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/40 Spotlight.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-40.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/80 Retina Spotlight.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-40@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/58 Retina Setting.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/114 App Icon.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/72 Home Screen iOS6.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-72.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/144 Retina Home Screen iOS6.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-72@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/50 Retina Spotlight iOS6.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-50.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/100 Retina Spotlight iOS6.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-50@2x.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default~iphone.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default~iphone.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default@2x~iphone_640x960.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default@2x~iphone.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-Portrait~ipad_768x1024.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-Portrait~ipad.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-Portrait@2x~ipad_1536x2048.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-Portrait@2x~ipad.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-Landscape~ipad_1024x768.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-Landscape~ipad.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-Landscape@2x~ipad_2048x1536.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-Landscape@2x~ipad.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-568h@2x~iphone_640x1136.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-568h@2x~iphone.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-667h.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-667h.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-736h.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-736h.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-Landscape-736h.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-Landscape-736h.png
iOS Product Name has not changed (still "me")
cordova-custom-config: Running applyCustomConfig.js
cordova-custom-config: package.json already exists
cordova-custom-config: Copied existing package.json to package.json.tmp
cordova-custom-config: Copying package.json
cordova-custom-config: Copied package.json
cordova-custom-config: Installing plugin dependencies...
cordova-custom-config: Running npm install
cordova-custom-config: Completed npm install
cordova-custom-config: Installed modules
cordova-custom-config: package.json.tmp exists
cordova-custom-config: Overwrote our package.json with original package.json.tmp
cordova-custom-config: Removing package.json.tmp
cordova-custom-config: Removed package.json.tmp
cordova-custom-config: Dependency resolution complete
cordova-custom-config: Created backup directory: /Users/mikechamberlain/dev/simple/client/plugins/cordova-custom-config/backup
cordova-custom-config: Created backup platform directory: /Users/mikechamberlain/dev/simple/client/plugins/cordova-custom-config/backup/ios
cordova-custom-config: Backed up /Users/mikechamberlain/dev/simple/client/platforms/ios/me.xcodeproj/project.pbxproj to /Users/mikechamberlain/dev/simple/client/plugins/cordova-custom-config/backup/ios/project.pbxproj
cordova-custom-config: Applied custom config from config.xml to /Users/mikechamberlain/dev/simple/client/platforms/ios/me.xcodeproj/project.pbxproj
cordova-custom-config: Reading build.xcconfig
cordova-custom-config: Reading build-extras.xcconfig
cordova-custom-config: Reading build-debug.xcconfig
cordova-custom-config: Reading build-release.xcconfig
cordova-custom-config: Backed up /Users/mikechamberlain/dev/simple/client/platforms/ios/me/me-Info.plist to /Users/mikechamberlain/dev/simple/client/plugins/cordova-custom-config/backup/ios/me-Info.plist
cordova-custom-config: Applied custom config from config.xml to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/me-Info.plist
cordova-custom-config: Write to plist; key=NSAppTransportSecurity; value={
  NSAllowsArbitraryLoads: true
}
cordova-custom-config: Write to plist; key=UISupportedInterfaceOrientations; value=[
  'UIInterfaceOrientationPortrait',
  'UIInterfaceOrientationPortraitUpsideDown',
  'UIInterfaceOrientationLandscapeLeft',
  'UIInterfaceOrientationLandscapeRight'
]
cordova-custom-config: Finished applying platform config
cordova-custom-config: replace XCBuildConfiguration key={ ENABLE_BITCODE } to value={ "NO" } for build type='Debug' in block='1D6058940D05DD3E006BFB54'
cordova-custom-config: replace XCBuildConfiguration key={ ENABLE_BITCODE } to value={ "NO" } for build type='Release' in block='1D6058950D05DD3E006BFB54'
mikebook:client mikechamberlain$ cordova build
Running command: /Users/mikechamberlain/dev/simple/client/build/ios/before_prepare-hook.sh /Users/mikechamberlain/dev/simple/client
cordova-custom-config: Installing plugin dependencies...
^C
mikebook:client mikechamberlain$ 
mikebook:client mikechamberlain$ 
mikebook:client mikechamberlain$ cordova build -verbose
Running command: /Users/mikechamberlain/dev/simple/client/build/ios/before_prepare-hook.sh /Users/mikechamberlain/dev/simple/client
Command finished with error code 0: /Users/mikechamberlain/dev/simple/client/build/ios/before_prepare-hook.sh /Users/mikechamberlain/dev/simple/client
cordova-custom-config: Running restoreBackups.js
cordova-custom-config: package.json already exists
cordova-custom-config: Copied existing package.json to package.json.tmp
cordova-custom-config: Copying package.json
cordova-custom-config: Copied package.json
cordova-custom-config: Installing plugin dependencies...
cordova-custom-config: Running npm install
cordova-custom-config: Completed npm install
cordova-custom-config: Installed modules
cordova-custom-config: package.json.tmp exists
cordova-custom-config: Overwrote our package.json with original package.json.tmp
cordova-custom-config: Removing package.json.tmp
cordova-custom-config: Removed package.json.tmp
cordova-custom-config: Dependency resolution complete
cordova-custom-config: Checking to see if there are backups to restore...
cordova-custom-config: Restored backup of 'me-Info.plist' to :/Users/mikechamberlain/dev/simple/client/platforms/ios/me/me-Info.plist
cordova-custom-config: Restored backup of 'project.pbxproj' to :/Users/mikechamberlain/dev/simple/client/platforms/ios/me.xcodeproj/project.pbxproj
cordova-custom-config: Finished restoring backups
Generating config.xml from defaults for platform "ios"
Calling plugman.prepare for platform "ios"
Preparing ios project
Processing configuration changes for plugins.
Iterating over installed plugins: [ 'cordova-plugin-whitelist',
  'cordova-plugin-customurlscheme',
  'cordova-plugin-inappbrowser',
  'cordova-plugin-statusbar',
  'org.apache.cordova.splashscreen',
  'cordova-plugin-app-version',
  'cordova-plugin-network-information',
  'cordova-plugin-appavailability',
  'nl.x-services.plugins.touchid',
  'com.shazron.cordova.plugin.keychainutil',
  'cordova-plugin-x-socialsharing',
  'phonegap-plugin-push',
  'cordova-plugin-badge',
  'cordova-custom-config',
  'cordova-plugin-app-event' ]
Writing out cordova_plugins.js...
Wrote out iOS Bundle Identifier to "com.macquarie.cog.digital.simple"
Wrote out iOS Bundle Version to "1.4.0"
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/60 Home Screen.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-60.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/120 Retina Home Screen.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-60@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/180 Retina App Icon.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-60@3x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/76 Home Screen.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-76.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/152 Retina Home Screen.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-76@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/29 Settings.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-small.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/58 Retina Setting.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-small@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/40 Spotlight.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-40.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/80 Retina Spotlight.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-40@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/58 Retina Setting.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/114 App Icon.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/72 Home Screen iOS6.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-72.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/144 Retina Home Screen iOS6.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-72@2x.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/50 Retina Spotlight iOS6.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-50.png
Copying icon from /Users/mikechamberlain/dev/simple/client/build/assets/ios/icons/100 Retina Spotlight iOS6.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/icons/icon-50@2x.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default~iphone.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default~iphone.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default@2x~iphone_640x960.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default@2x~iphone.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-Portrait~ipad_768x1024.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-Portrait~ipad.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-Portrait@2x~ipad_1536x2048.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-Portrait@2x~ipad.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-Landscape~ipad_1024x768.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-Landscape~ipad.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-Landscape@2x~ipad_2048x1536.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-Landscape@2x~ipad.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-568h@2x~iphone_640x1136.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-568h@2x~iphone.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-667h.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-667h.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-736h.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-736h.png
Copying splash from /Users/mikechamberlain/dev/simple/client/build/assets/ios/splash/Default-Landscape-736h.png to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/Resources/splash/Default-Landscape-736h.png
iOS Product Name has not changed (still "me")
Running command: /Users/mikechamberlain/dev/simple/client/build/ios/after_prepare-hook.sh /Users/mikechamberlain/dev/simple/client
Updating Plist file...
Plist file updated
Command finished with error code 0: /Users/mikechamberlain/dev/simple/client/build/ios/after_prepare-hook.sh /Users/mikechamberlain/dev/simple/client
cordova-custom-config: Running applyCustomConfig.js
cordova-custom-config: package.json already exists
cordova-custom-config: Copied existing package.json to package.json.tmp
cordova-custom-config: Copying package.json
cordova-custom-config: Copied package.json
cordova-custom-config: Installing plugin dependencies...
cordova-custom-config: Running npm install
cordova-custom-config: Completed npm install
cordova-custom-config: Installed modules
cordova-custom-config: package.json.tmp exists
cordova-custom-config: Overwrote our package.json with original package.json.tmp
cordova-custom-config: Removing package.json.tmp
cordova-custom-config: Removed package.json.tmp
cordova-custom-config: Dependency resolution complete
cordova-custom-config: Backup exists for 'project.pbxproj' at: /Users/mikechamberlain/dev/simple/client/plugins/cordova-custom-config/backup/ios/project.pbxproj
cordova-custom-config: Applied custom config from config.xml to /Users/mikechamberlain/dev/simple/client/platforms/ios/me.xcodeproj/project.pbxproj
cordova-custom-config: Reading build.xcconfig
cordova-custom-config: Reading build-extras.xcconfig
cordova-custom-config: Reading build-debug.xcconfig
cordova-custom-config: Reading build-release.xcconfig
cordova-custom-config: Backup exists for 'me-Info.plist' at: /Users/mikechamberlain/dev/simple/client/plugins/cordova-custom-config/backup/ios/me-Info.plist
cordova-custom-config: Applied custom config from config.xml to /Users/mikechamberlain/dev/simple/client/platforms/ios/me/me-Info.plist
cordova-custom-config: Write to plist; key=NSAppTransportSecurity; value={
  NSAllowsArbitraryLoads: true
}
cordova-custom-config: Write to plist; key=UISupportedInterfaceOrientations; value=[
  'UIInterfaceOrientationPortrait',
  'UIInterfaceOrientationPortraitUpsideDown',
  'UIInterfaceOrientationLandscapeLeft',
  'UIInterfaceOrientationLandscapeRight'
]
cordova-custom-config: Finished applying platform config
Running command: /Users/mikechamberlain/dev/simple/client/platforms/ios/cordova/build 
cordova-custom-config: replace XCBuildConfiguration key={ ENABLE_BITCODE } to value={ "NO" } for build type='Debug' in block='1D6058940D05DD3E006BFB54'
cordova-custom-config: replace XCBuildConfiguration key={ ENABLE_BITCODE } to value={ "NO" } for build type='Release' in block='1D6058950D05DD3E006BFB54'

```

**Comment by dpa99c** [comment] 2016-02-25 21:12
Just published cordova-custom-config@1.2.5
This should hopefully resolve the issue (which I think is a race condition of overlapping hooks during the build phase) by only attempting to resolve dependencies using npm during backup/restore or apply config operations if an error occurred while trying to load a dependent module.

Please give this a try and let me know if it fixes the issue.

See #31 as to why this was introduced (due to a rework of dependency resolution).

**Comment by mikechamberlain** [comment] 2016-02-26 02:34
Yes, this is much better now, and quicker too.  Thanks!

**Comment by dpa99c** [comment] 2016-02-26 21:40
@GitRubb @johnkcox let me know if it's fixed now for you too and I'll close this

**Comment by GitRubb** [comment] 2016-02-29 18:15
Thanks @dpa99c for the fix, I won't be able to test it right now but will be sure to comment if I see any issues.

**Comment by dpa99c** [comment] 2016-03-02 21:08
Re-open if still an issue

**Closed by dpa99c** 2016-03-02 21:08 UTC

**Comment by thiphariel** [comment] 2016-04-04 14:03
Reopened it cause even 1.2.6 rewrite my top-level package.json file... Any suggestion why it does it ?
Will paste it a verbose installation...
