### ISSUE TITLE
AndroidManifest.xml path changed in cordova 7.0.0 

### ISSUE THREAD

**Issue by kannanmaran** [dpa99c/cordova-custom-config#141] opened 2018-02-21 06:59 UTC
AndroidManifest.xml path has changed in cordova 7.0.0 (android/app/src/main/)

**Comment by dpa99c** [comment] 2018-02-21 09:03
This is a duplicate of #135 which was fixed by commit [103b457](https://github.com/dpa99c/cordova-custom-config/commit/103b4579b7696c50026d775b6f78bf588b3f7c3e) on 7 Dec 2017 and published in v5.0.1.

**Closed by dpa99c** 2018-02-21 09:03 UTC
