### ISSUE TITLE
Cocoon iOS Config XML Corruption

### ISSUE THREAD

**Issue by LordMalc** [dpa99c/cordova-custom-config#37] opened 2016-02-16 12:30 UTC
When I install the plugin into my Cocoon project, without even making any config.xml changes, the app loses its icon, splash screen and orientation. Those are just a few observations; I'm assuming it's completely ignoring all XML.

I've tried so many tests to get around this and now out of options.

Any ideas at all?

Thanks,

Malc

**Comment by dpa99c** [comment] 2016-02-16 13:19
Without seeing your config.xml and the resulting console output, it's difficult to know the exact cause. If you run Cordova CLI operations with the `--verbose` option, the plugin will output detailed info e.g. `cordova build ios --verbose`

By default, the plugin makes [backups](https://github.com/dpa99c/cordova-custom-config#backups) of project config files (on iOS: plist, project.pbxproj) and restores them using a before_prepare hook before applying custom config using an after_prepare hook. It does so to make custom config preferences added by the plugin "removable".

I haven't used Cocoon, but I assume it's some wrapper for Cordova. In which case, if it's also making modifications to the iOS platform config files, then it's possible this is conflicting with this plugin.

You can disable the auto-backup/restore behaviour, by add this preference to your config.xml:

    <preference name="cordova-custom-config-autorestore" value="true" />

**Comment by LordMalc** [comment] 2016-02-16 14:21
Hi dpa99c,

Unfortunately, I don't have verbose with Cocoon so can't provide any output. A big shame.

I've already implemented the auto-restore setting - no luck there.

Is there going to be a way that I can alter the .plist in the xarchive, after it's been compiled?

Here is my config.xml:

```
<?xml version="1.0" encoding="utf-8"?><widget xmlns="http://www.w3.org/ns/widgets" xmlns:cocoon="http://cocoon.io/ns/1.0" id="com.cc.bebods" version="1.0.0" ios-CFBundleVersion="1.0.33">
    <preference name="cordova-custom-config-autorestore" value="false"/>
    <name>bebods</name>
    <description>
        A sample Cocoon application that responds to the deviceready event.
    </description>
    <author email="Malcolm.Adams@completecontrol.co.uk" href="https://cocoon.io">
        Malcolm Adams
    </author>
    <content src="index.html"/>
    <plugin name="cordova-plugin-whitelist" version="1"/>
    <access origin="*"/>
    <allow-intent href="http://*/*"/>
    <allow-intent href="https://*/*"/>
    <allow-intent href="tel:*"/>
    <allow-intent href="sms:*"/>
    <allow-intent href="mailto:*"/>
    <allow-intent href="geo:*"/>
    <cocoon:plugin name="cordova-custom-config"/>
    <platform name="android">
        <allow-intent href="market:*"/>
    </platform>
    <platform name="ios">
        <config-file platform="ios" target="*-Info.plist" parent="NSAppTransportSecurity">
            <dict>
                <key>NSAllowsArbitraryLoads</key>
                <true/>
            </dict>
        </config-file>
        <allow-intent href="itms:*"/>
        <allow-intent href="itms-apps:*"/>
        <preference name="Orientation" value="landscape"/>
        <preference name="Fullscreen" value="true"/>
    </platform>
    <cocoon:platform enabled="false" name="android"/>
    <preference name="CocoonSplashDelay" value="2"/>
    <cocoon:plugin name="https://github.com/rafelbev/cordova-plugin-ipad-multitasking.git"/>
    <cocoon:plugin name="cordova-plugin-network-information"/>
</widget>
```

**Comment by LordMalc** [comment] 2016-02-16 15:24
I uninstalled the network plugin and moved the xml nodes around a little and it no longer broke. I then put everything back and it still worked. Very odd.

So, with the builds now going through correctly, unfortunately, after all that, I still wasn't able to get HTTP access. I broke apart the ipa and could see that I had actually successfully applied the NSAppTransportSecurity setting in the .plist file...

...but it still doesn't allow access to HTTP!

Why? :frowning:

**Comment by dpa99c** [comment] 2016-02-17 08:27
You have cordova-plugin-whitelist in your config.xml too - have you whitelisted access for this in the Content meta tag?

**Comment by LordMalc** [comment] 2016-02-17 11:38
Sorry dpa99c, I'm not sure what you mean by the content meta tag...

Do you mean:

- The <content> node, in my xml above?
- The <meta> tags of any pages being loaded?
- Neither of these - something completely different?

Thanks dpa99c, really appreciating this and it's very important to us to try and fix the problem, as we're about to move on to another technology and I would prefer to see if we can get this working first... we're so close!


Malc

**Comment by dpa99c** [comment] 2016-02-18 12:14
Since you're using [cordova-plugin-whitelist](https://github.com/apache/cordova-plugin-whitelist), make sure you have set something lax enough for the [network request whitelist](https://github.com/apache/cordova-plugin-whitelist#network-request-whitelist) e.g. `<access origin="*" />` and/or the [content security policy](https://github.com/apache/cordova-plugin-whitelist#content-security-policy) e.g. `<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'">`

Closing this as an issue as it's not caused by this plugin.

**Closed by dpa99c** 2016-02-18 12:14 UTC
