### ISSUE TITLE
No write file AndroidManifest.xml in OS X 10.11.4 and node 5.10.1

### ISSUE THREAD

**Issue by orcoliver** [dpa99c/cordova-custom-config#46] opened 2016-04-22 20:06 UTC
Hi!,
The hook no write changes in file. I change the line:
```javascript
fs.writeFileSync(targetFilePath, tempManifest.write({indent: 4}), 'utf-8');
```
to
```javascript
fs.writeFileSync(targetFilePath, tempManifest.write({indent: 4}), 'utf-8', (err) => {if(err) throw err;});
```
and this work.
Regards

**Comment by orcoliver** [comment] 2016-04-22 20:26
Sometimes write changes, sometimes no write changes.

**Comment by dpa99c** [comment] 2016-04-23 07:07
This is not information to diagnose if there is an issue - the versions of OSX and node are somewhat irrelevant. Please provide the following information:

- Version of this plugin with which the issue was observed
- Version of Cordova CLI
- The **entire** verbose output of a "failed" build or prepare operation: `cordova prepare android --verbose` or `cordova build android --verbose`
- The contents of your `config.xml`

Without this information, it won't be possible to diagnose a problem and this issue will be closed.

**Comment by GitRubb** [comment] 2016-04-28 22:11
I'm seeing the same issue, fs.writeFileSync is not writing the updated AndroidManifest.xml.
OS X 10.11.4 and Node version 4.4.3. 

Here's some other similarly reported issues: 
https://github.com/jprichardson/node-fs-extra/issues/238
http://stackoverflow.com/questions/36916155/nodejsfs-write-callback-and-fs-writefile-not-working

**Comment by GitRubb** [comment] 2016-04-28 22:25
Found out the issue (at least for my case), it was a plugin trying to reinstall itself after the prepare completes.

cordova-custom-config: Applied custom config from config.xml to /.../platforms/android/AndroidManifest.xml
Discovered plugin "cordova-plugin-intent" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-intent@~0.1.2" via npm
Plugin "com.napolitano.cordova.plugin.intent" already installed on android.

If you have a plugin installed with a different name then what's listed in its plugin.xml id, cordova custom config will try to re-install the plugin, when that happens the Android xml changes are reverted.

**Comment by dpa99c** [comment] 2016-05-12 12:08
@GitRubb cordova-custom-config does not perform any re-installation of plugins - these operations are being performed by Cordova itself. This is evident from the log output you have posted, because all log messages from cordova-custom-config are prefixed with `cordova-custom-config:`.

cordova-custom-config applies its configuration changes using an `after_prepare` hook, which is the latest point in the prepare process it has access to. If the Cordova CLI comes along afterwards and resets those changes, there's nothing this plugin can do about it. 

I'm going to close this issue as the OP has failed to provide sufficient information to diagnose his problem, however if you're able to consistently reproduce an issue, please open it separately.

**Closed by dpa99c** 2016-05-12 12:08 UTC
Labels: more info needed
